Laboratorio 1 automatización: Maria Jose Bedoya Carmona, María José Rodríguez Gómez, Karen Olarte



**A**. **Definicion de** *def*:

Es una palabra clave usada para crear o definir una función, es decir, un bloque de código con nombre específico que almacena instrucciones para realizar una tarea determinada. Esta función puede ser llamada a lo largo del código para ejecutar dicho bloque.


In [2]:
#Ejemplo: sumar dos números
a = int(input("Ingrese el primer número: "))
b = int(input("Ingrese el segundo número: "))
def suma(a, b):
  return a + b
resultado = suma(a, b)
print("El resultado de la suma es: ", resultado)

ValueError: invalid literal for int() with base 10: ''

**B.** Desarrolle una calculadora básica usando funciones, en la cual ingresen 2 números enteros y el
tipo de operación a realizar en string. Como resultado la calculadora debe arrojar la operación
deseada entre los 2 números.

In [3]:
Num_1=int(input("Ingrese el primer número: "))
Num_2=int(input("Ingrese el segundo número: "))
#Definir las operaciones
def suma(Num_1, Num_2):
  return Num_1+Num_2
Suma=suma(Num_1, Num_2)
def resta(Num_1, Num_2):
  return Num_1-Num_2
Resta=resta(Num_1, Num_2)
def mul(Num_1,Num_2):
  return Num_1*Num_2
Mul=mul(Num_1, Num_2)
def div(Num_1, Num_2):
  if Num_2 == 0:
    print("No se puede dividir entre cero")
  else:
    return Num_1/Num_2
Div=div(Num_1, Num_2)
def mod(Num_1, Num_2):
  if Num_2 == 0:
    print("No se puede dividir entre cero")
  else:
    return Num_1%Num_2
Mod=mod(Num_1, Num_2)
print("Operaciones : ", "\n", "1:Suma (+)", "\n", "2:Resta (-)", "\n", "3:Multiplicación (*)", "\n", "4:División (/)", "\n", "5:Modulo (%)")
Op=input("Ingrese el número de operación que desea realizar: ")


if Op == "1":
  resultado = Suma
elif Op == "2":
  restultado = Resta
elif Op == "3":
  resultado = Mul
elif Op == "4":
  resultado = Div
elif Op == "5":
  resultado = Mod
else:
  print("Error: Operación incorrecta")
print("El resultado de la operación es:", resultado)

ValueError: invalid literal for int() with base 10: ''

**C.** Desarrolle un algoritmo en el cual usted pueda definir el tamaño de una matriz cuadrada con
un numero N, posteriormente le pida cada uno de los valores de la matriz con la indicación
exacta de donde ira ubicado. Finalmente, el algoritmo debe retornar al usuario la matriz
deseada y su transpuesta.

In [16]:
import numpy as np
n = int(input("Ingrese el tamaño de la matriz: "))
matriz = np.zeros((n,n))
for x in range(n):
  for y in range(n):
    print("valor para la posicion(",x+1,",",y+1,"): ",end="")
    matriz[x][y] =float(input())
print("matriz ingresada\n", matriz)
print("matriz transpuesta:\n", np.transpose(matriz))


Ingrese el tamaño de la matriz: 2
valor para la posicion( 1 , 1 ): 2
valor para la posicion( 1 , 2 ): 3.5
valor para la posicion( 2 , 1 ): 1.2
valor para la posicion( 2 , 2 ): 2
matriz ingresada
 [[2.  3.5]
 [1.2 2. ]]
matriz transpuesta:
 [[2.  1.2]
 [3.5 2. ]]


D. Desarrolle un algoritmo que reciba un mes y día especifico, y nos dé una aproximación para esa
fecha sobre la estación climática en la cual estamos.

In [15]:
#Se desarrollo con base en las fechas de las estaciones en el hemisferio Norte
def estacion(dia, mes):
  #Definir los meses y el número de días por mes
  meses = {
      "enero":31, "febrero" :28, "marzo":31, "abril":30, "mayo":31, "junio":30, "julio":31, "agosto":31, "septiembre":30, "octubre":31, "noviembre":30, "diciembre":31
  }
  #Clave: Nombre del mes
  #Valor: Cantidad de días del mes

  mes=mes.lower().strip()              #.lower va a convertir la entrada a minúsculas para que coincida con la clave del diccionario
  if mes not in meses:                 #.strip va a eliminar los espacios en blanco al principio y al final del texto ingresados por el usuario
    return "Mes inválido"

  if dia < 1 or dia > meses[mes]:
    return "Día inválido"

  #Definir las condiciones
  if (mes == "marzo" and dia >= 20) or (mes in ["abril","mayo"]) or (mes == "junio" and dia <= 20):
    estacion = "Primavera"
  elif (mes == "junio" and dia > 20) or (mes in ["julio", "agosto"]) or (mes == "septiembre" and dia <= 23):
    estacion = "verano"
  elif (mes == "septiembre" and dia > 23) or (mes in ["octubre", "noviembre"]) or (mes == "diciembre" and dia <= 22):
    estacion = "otoño"
  else:
    estacion = "Invierno"

  return (f"Para el día {dia} del mes de {mes} estaríamos en {estacion}")

# Obtener primero la entrada del mes, luego el día
mes = str(input("Ingrese el mes que desea consultar: "))
dia = int(input("Ingrese el día del mes que desea consultar: "))

print(estacion(dia, mes)) #Llamamos la función definida inicialmente

Ingrese el mes que desea consultar: febrero 
Ingrese el día del mes que desea consultar: 30 
Día inválido


E. Desarrolle un algoritmo que sea capaz de sumar una matriz aleatoria con una matriz ingresada
por el usuario

In [24]:
import numpy as vextor
x=int(input("Ingrese el numero de filas: "))
y=int(input("Ingrese el numero de columnas: "))
Matrizale=vextor.random.randint(10, size=(x,y))
print("Matriz Aleatoria \n",Matrizale)
Matrizusu=vextor.zeros((x,y))

for i in range(Matrizusu.shape[0]):
  for j in range(Matrizusu.shape[1]):
    Matrizusu[i,j]=float(input(f"valor para la posicion({i+1},{j+1}): "))
print("Matriz del Usuario \n",Matrizusu)
print("Suma de las Matrices \n",Matrizusu+Matrizale)

Ingrese el numero de filas: 2
Ingrese el numero de columnas: 2
Matriz Aleatoria 
 [[8 5]
 [0 4]]
valor para la posicion(1,1): 3
valor para la posicion(1,2): 4
valor para la posicion(2,1): 6
valor para la posicion(2,2): 2
Matriz del Usuario 
 [[3. 4.]
 [6. 2.]]
Suma de las Matrices 
 [[11.  9.]
 [ 6.  6.]]


F. Una empresa de comercio electrónico necesita un programa en Python que procese reseñas de
clientes.
El programa debe:
1. Pedir al usuario que ingrese varias reseñas de productos (mínimo 3).
2. Convertir todas las reseñas a minúsculas y eliminar signos de puntuación básicos (. , ! ?).
3. Guardar cada reseña en una lista.
4. Crear un diccionario de frecuencias que indique cuántas veces aparece cada palabra en
todas las reseñas combinadas.
5. Identificar y mostrar:
Las 3 palabras más frecuentes en las reseñas.

In [67]:
import string
reseñas = []
while True:
    num_res = int(input("Ingrese el número de reseñas: "))
    if num_res < 3:
        print("Error: El número de reseñas es inválido")
        continue  # Regresa al inicio
    for i in range (num_res):
      reseña = input("Ingrese la reseña: ")
      reseña = reseña.lower().translate(str.maketrans('', '', string.punctuation))
      reseñas.append(reseña)
    f = {}                  #Diccionario de frecuencias
    for reseña in reseñas:
      for palabra in reseña.split():  # Dividir cada reseña palabra por palabra
            if palabra in f:
                f[palabra] += 1
            else:
                f[palabra] = 1
    dic_asc = sorted(f.items(), key=lambda item: item[1], reverse = True)
    palabras_frec = dic_asc[:3]
    print("Las tres palabras más frecuentes en las reseñas son:\n" +
      "\n".join([f"{p}: {c}" for p, c in palabras_frec]))
    break

Ingrese el número de reseñas: 4
Ingrese la reseña: feo 
Ingrese la reseña: muy feo 
Ingrese la reseña: lindo 
Ingrese la reseña: feo
Las tres palabras más frecuentes en las reseñas son:
feo: 3
muy: 1
lindo: 1
